add_spl_target(00-SPL-Template  exercises/00-SPL-Template/main.c)
add_spl_target(02-SPL-Histogramm  exercises/02-SPL-Histogramm/main.c)
add_spl_target(03-SPL-BMIRechner  exercises/03-SPL-BMIRechner/main.c)
add_spl_target(03-SPL-Fibonacci  exercises/03-SPL-Fibonacci/main.c)
add_spl_target(03-SPL-Multiplikationstabelle  exercises/03-SPL-Multiplikationstabelle/main.c)
add_spl_target(03-SPL-Smiley  exercises/03-SPL-Smiley/main.c)
add_spl_target(04-SPL-BallMitPhysik  exercises/04-SPL-BallMitPhysik/main.c)
add_spl_target(04-SPL-Hailstone  exercises/04-SPL-Hailstone/main.c)
add_spl_target(04-SPL-Pyramide  exercises/04-SPL-Pyramide/main.c)
add_spl_target(04-SPL-Zielscheibe  exercises/04-SPL-Zielscheibe/main.c)
add_spl_target(05-SPL-BMI-by-Reference  exercises/05-SPL-BMI-by-Reference/main.c)
add_spl_target(05-SPL-Call-by-Reference  exercises/05-SPL-Call-by-Reference/main.c)
add_spl_target(06-SPL-AnswerPhone exercises/06-SPL-AnswerPhone/test.c exercises/06-SPL-AnswerPhone/main.c)
add_spl_target(06-SPL-Club exercises/06-SPL-Club/test.c exercises/06-SPL-Club/main.c)
add_spl_target(06-SPL-Kreise  exercises/06-SPL-Kreise/main.c)
add_spl_target(06-SPL-noThirteenSum exercises/06-SPL-noThirteenSum/test.c exercises/06-SPL-noThirteenSum/main.c)
add_spl_target(06-SPL-SquirrelParty exercises/06-SPL-SquirrelParty/test.c exercises/06-SPL-SquirrelParty/main.c)
add_spl_target(06-SPL-sumNoTeens exercises/06-SPL-sumNoTeens/test.c exercises/06-SPL-sumNoTeens/main.c)
add_spl_target(07-SPL-CarSimulator  exercises/07-SPL-CarSimulator/main.c)
add_spl_target(07-SPL-Lucky13 exercises/07-SPL-Lucky13/test.c exercises/07-SPL-Lucky13/main.c)
add_spl_target(07-SPL-Notenhaeufigkeit  exercises/07-SPL-Notenhaeufigkeit/main.c)
add_spl_target(07-SPL-swapEnds exercises/07-SPL-swapEnds/test.c exercises/07-SPL-swapEnds/main.c)
add_spl_target(07-SPL-Unlucky1 exercises/07-SPL-Unlucky1/test.c exercises/07-SPL-Unlucky1/main.c)
add_spl_target(08-SPL-Buchstabenhaeufigkeit  exercises/08-SPL-Buchstabenhaeufigkeit/main.c)
add_spl_target(08-SPL-PasswordChecker  exercises/08-SPL-PasswordChecker/main.c)
add_spl_target(08-SPL-ScrabbleScore  exercises/08-SPL-ScrabbleScore/main.c)
add_spl_target(09-SPL-Durchschnittsnoten  exercises/09-SPL-Durchschnittsnoten/main.c)
add_spl_target(09-SPL-NumberDelimiter  exercises/09-SPL-NumberDelimiter/main.c)
add_spl_target(09-SPL-Sichtbarkeit-2  exercises/09-SPL-Sichtbarkeit-2/main.c)
add_spl_target(09-SPL-Sichtbarkeit  exercises/09-SPL-Sichtbarkeit/main.c)
add_spl_target(09-SPL-SudokuChecker  exercises/09-SPL-SudokuChecker/main.c)
add_karel_target(00-Karel-Template  exercises/00-Karel-Template/main.c)
add_karel_target(01-Karel-DamagedPillars  exercises/01-Karel-DamagedPillars/main.c)
add_karel_target(01-Karel-Flag  exercises/01-Karel-Flag/main.c)
add_karel_target(01-Karel-Livingroom  exercises/01-Karel-Livingroom/main.c)
add_karel_target(01-Karel-SteepleChase  exercises/01-Karel-SteepleChase/main.c)
add_karel_target(02-Karel-ClimbTwoPyramids  exercises/02-Karel-ClimbTwoPyramids/main.c)
add_karel_target(02-Karel-DiamondMining  exercises/02-Karel-DiamondMining/main.c)
